version: '3'

services:
  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    restart: always
    environment:
      - TZ=Europe/Madrid
      - SUBDOMAINS=SUBDOMAIN
      - TOKEN=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
      - LOG_FILE=false #optional

  nginx-proxy:
    image: budry/jwilder-nginx-proxy-arm
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt-nginx-proxy:
    image: duch/letsencrypt-nginx-proxy-companion:stable
    container_name: letsencrypt-nginx-proxy
    restart: always
    volumes:
      - certs:/etc/nginx/certs:rw
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - /home/USER/sharedrpi:/usr/share/nginx/html:ro
      - /scripts/docker/nginx/default:/etc/nginx/sites-enabled/default:ro
      - /scripts/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /scripts/docker/nginx/htpasswd:/etc/nginx/.htpasswd:ro
    environment:
      - VIRTUAL_HOST=DOMAIN.COM
      - LETSENCRYPT_HOST=DOMAIN.COM
      - LETSENCRYPT_EMAIL=USER@DOMAIN.COM

volumes:
  certs:
  html:
  vhostd:
  confd:
